// File generated by FlutterFire CLI and modified to use environment variables.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB'),
    appId: '1:883656038491:web:4073fee51ce1240a58477e',
    messagingSenderId: '883656038491',
    projectId: 'jala-e3484',
    authDomain: 'jala-e3484.firebaseapp.com',
    storageBucket: 'jala-e3484.firebasestorage.app',
    measurementId: 'G-FN71VCQ5VH',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID'),
    appId: '1:883656038491:android:b51c0b5699a90eaa58477e',
    messagingSenderId: '883656038491',
    projectId: 'jala-e3484',
    storageBucket: 'jala-e3484.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
    appId: '1:883656038491:ios:166d5fbd537e2eaa58477e',
    messagingSenderId: '883656038491',
    projectId: 'jala-e3484',
    storageBucket: 'jala-e3484.firebasestorage.app',
    iosBundleId: 'com.uriel.viajeseguroapp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
    appId: '1:883656038491:ios:166d5fbd537e2eaa58477e',
    messagingSenderId: '883656038491',
    projectId: 'jala-e3484',
    storageBucket: 'jala-e3484.firebasestorage.app',
    iosBundleId: 'com.uriel.viajeseguroapp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB'),
    appId: '1:883656038491:web:ff6b28aae877b4a358477e',
    messagingSenderId: '883656038491',
    projectId: 'jala-e3484',
    authDomain: 'jala-e3484.firebaseapp.com',
    storageBucket: 'jala-e3484.firebasestorage.app',
    measurementId: 'G-ZMSKSPPJVM',
  );
}
